export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE'; // 用户状态改变
export const USER_TOKEN_CHANGE = 'USER_TOKEN_CHANGE'; // 用户token改变
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'; // 更新用户信息
export const GET_USER_SHOP_DATA = 'GET_USER_SHOP_DATA'; // 获取用户店铺数据
export const GET_FAQ_DATA = 'GET_FAQ_DATA'; // 获取常见问题数据
export const GET_FEEDBACK_DATA = 'GET_FEEDBACK_DATA'; // 获取吐槽选项数据
export const GET_RECHARGE_DATA = 'GET_RECHARGE_DATA'; // 获取充值面额列表数据
export const GET_ORDER_STATE_NUM = 'GET_ORDER_STATE_NUM'; // 获取订单状态数量数据
export const GET_CART_TOTAL_NUM = 'GET_CART_TOTAL_NUM'; // 获取购物车数量
export const GET_USER_MESSAGE_DATA = 'GET_USER_MESSAGE_DATA'; // 获取未读消息分组数量
export const UPDATE_USER_INFO_LOADING = 'UPDATE_USER_INFO_LOADING'; // 更新用户信息开始等待
export const GET_UNREAD_ALL_COUNT = 'GET_UNREAD_ALL_COUNT'; // 获得用户未读消息数量
export const GET_USER_POINTS_SIGNINFO = 'GET_USER_POINTS_SIGNINFO'; // 查询用户是否签到和是否领取可领积分
export const GET_USER_CARD_LIST = 'GET_USER_CARD_LIST'; // 获取用户卡片列表
export const SET_UNREAD_MESSAGE_NUMBER = 'SET_UNREAD_MESSAGE_NUMBER'; // 设置未读消息数量
export const SET_USER_SHOP_LIST = 'SET_USER_SHOP_LIST'; // 设置用户店铺列表
export const GET_USER_SENDOLDPHONESMS = 'GET_USER_SENDOLDPHONESMS'// 原手机号获取验证码
export const GET_USER_MYDEMANDDETAIL = 'GET_USER_MYDEMANDDETAIL'// 我的客户详情页
export const GET_USER_AGENT_INFO = 'GET_USER_AGENT_INFO'// 获取用户代理信息

